apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug-blaster-frontend
  labels:
    app: bug-blaster-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bug-blaster-frontend
  template:
    metadata:
      labels:
        app: bug-blaster-frontend
    spec:
      serviceAccountName: admin
      containers:
        - name: bug-blaster-frontend
          image: huan1398/bug-blaster-frontend:latest
          ports:
          - containerPort: 3000
        #- name: bug-blaster-frontend-api-server
        #  image: huan1398/bug-blaster-frontend-api-server:latest
        #  ports:
        #  - containerPort: 3050
